inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'      # いったん config 全体を除外（routes/initializers 等のノイズを消す）
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'config.ru'
    - 'spec/**/*'        # まずはアプリ本体を通す。あとで戻したければ外す

plugins:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

# いまのコードはダブルクォート多め → それに合わせる
Style/StringLiterals:
  EnforcedStyle: double_quotes

# よく落ちる2つは最初は無効化（必要なら後で有効化）
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

# 旧名→新名で警告が出ていたやつ
Naming/PredicatePrefix:
  Enabled: true

# ネストしたクラス定義を強制するCop。まずは無効化（あとで直したければ有効化）
Style/ClassAndModuleChildren:
  Enabled: false
